groupsUrl:
  - https://raw.githubusercontent.com/bfitzgit23/stormos-calamares-xfce-config/master/etc/calamares/modules/netinstall-StormOS.yaml
  - file:///etc/calamares/modules/netinstall-stormos.yaml

required: false

label:
    sidebar: "StormOS Packages"
    sidebar[nl]: "StormOS Packages"
    sidebar[ja]: "StormOS 道具"
    title: "StormOS Packages"
    title[nl]: "StormOS Packages"
    title[ja]: "StormOS 道具"
